In [1]:
print('Hello world')

Hello world


NumPy
1. NumPy stands for Numerical Python, its a library consists of multidim array objects.
2. Using NumPy, mathematical and logica operations on arrays can be performed.

In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


ndarray
1. ndarray called as a N-dimensional array.
2. its a collection of items of same datatype.
3. every item in an ndarray takes the same size of memory block for storage.

##Creating Arrays in Python            
we can create array in python using list or tuple.

In [3]:
#from list to 1d array
import numpy as np
list1 = [1,2,3]
np.array(list1)

array([1, 2, 3])

In [4]:
type(np.array(list1))

numpy.ndarray

In [6]:
#from list to 2d array
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
#from list to 3d array
list_of_lists = [[[1,2,3],[4,5,6],[7,8,9]],[[4,6,7],[2,5,4],[7,8,9]],[[8,4,6],[4,5,6],[2,7,4]]]
np.array(list_of_lists)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[4, 6, 7],
        [2, 5, 4],
        [7, 8, 9]],

       [[8, 4, 6],
        [4, 5, 6],
        [2, 7, 4]]])

In [10]:
#basically, arrays are typically used in ML. if we want to process image then we use array.


`ndarray` is also known by the alias `array`. Note that `numpy.array` is not the same as the Standard Python Library class `array.array`, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an `ndarray` object are:

***Three types in ndarray:***           
                  
***ndarray.shape***
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, `shape` will be `(n,m)`. The length of the `shape` tuple is therefore the rank, or number of dimensions,`ndim`.

***ndarray.dtype***
an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

***ndarray.reshape***
Returns an array containing the same data with a new shape.

In [16]:
list1 = [1,2,3]
arr = np.array(list1)
arr


array([1, 2, 3])

In [18]:
print(arr)

[1 2 3]


In [20]:
type(np.array(list1))

numpy.ndarray

In [26]:
print(arr.dtype)     #showing the datatype of elements in array
print(arr.shape)    #1d array, has only x-axis.

int32
(3,)


In [29]:
#from list to 2d array
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
arr2 = np.array(list_of_lists)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
print(arr2.dtype)
print(arr2.shape)   #2d array, has x and y axis i.e o/p is 3,3

int32
(3, 3)


To create a new array using numpy

In [36]:
import numpy as np
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [39]:
arr = np.arange(0,10,3)     #3rd parameter is step
print(arr)

[0 3 6 9]


Generate new array using zeros or ones

In [43]:
np.zeros((2,3))     #rows,columns

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

Linespace (linspace)        
It is used to divide range of numbers in specified parts.

In [46]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

Generate Random Numbers      
Three types:              
1. rand
2. randn
3. randint

In [47]:
np.random.rand(2,5)     #rows,columns

array([[0.97061544, 0.5694663 , 0.30856318, 0.66456723, 0.15591889],
       [0.90152917, 0.73264692, 0.11796433, 0.4703107 , 0.93441635]])

In [50]:
np.random.randn(3,3)    #values based on standard normal distribution

array([[ 1.12435284,  0.06565814,  0.24961982],
       [ 0.58960817,  0.56501313,  0.32716958],
       [-0.84156063,  0.08842991,  1.17069641]])

In [56]:
np.random.randint(3,10,5)   #rangestart,rangeend,numberofelements

array([4, 8, 6, 6, 8])

Pandas

Panda's Four Data Structures:
1. Series: 1d array
2. Data frame: 2d array
3. Panel: 3d array
4. Panel 4D: 4d array

1. SERIES

In [57]:
#1. Series
#We already know that Series is a single column where as a Dataframe is a collection of multiple columns.
# A series is very similar to NumPy array
#The major difference is, series have labeled index means it can be indexed using label unlike numpy array which has only number index.
#label index means we can create index of particular values of a column.


In [58]:
#to create a Series
#we can create series using list or numpy array or dictionary

In [70]:
#using List
import pandas as pd
list1 = [10,20,30,40,50]
s1 = pd.Series(list1)

In [71]:
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [72]:
type(s1)

pandas.core.series.Series

In [86]:
print(s1.index)
print(s1.values)   #automatically converts Series into Array
print(s1.items)

RangeIndex(start=0, stop=5, step=1)
[10 20 30 40 50]
<bound method Series.items of 0    10
1    20
2    30
3    40
4    50
dtype: int64>


In [106]:
#using NumPy Array
import numpy as np
import pandas as pd

index = ['a','b','c']
l1 = [10,20,30]

arr = np.array(l1)  #NumPy array is created
s1 = pd.Series(arr)     #default index
s2 = pd.Series(index=index,data=arr)    #passing userdefined index and array of data
s3 = pd.Series(index=index, data=l1)


In [107]:
arr

array([10, 20, 30])

In [108]:
s1

0    10
1    20
2    30
dtype: int32

In [109]:
s2          #from NumPy array

a    10
b    20
c    30
dtype: int32

In [110]:
s3          #from list

a    10
b    20
c    30
dtype: int64

In [80]:
type(s2)

pandas.core.series.Series

In [84]:
print(s2.index)
print(s2.values)
print(s2.items)

Index(['a', 'b', 'c'], dtype='object')
[10 20 30]
<bound method Series.items of a    10
b    20
c    30
dtype: int32>


In [92]:
#creating Series from Dictionary
d1 = {'a':10,'b':20,'c':30}
s3 = pd.Series(d1)
s3


a    10
b    20
c    30
dtype: int64

In [96]:
print(s3.index)     #not key is used
print(s3.values)
print(s3.items)

Index(['a', 'b', 'c'], dtype='object')
[10 20 30]
<bound method Series.items of a    10
b    20
c    30
dtype: int64>


Using index in a Series

In [121]:
s1 = pd.Series(data=[1,2,3,4], index=['USA','UK','Germany','Australia'])
s2 = pd.Series(data=[1,2,3,4], index=['Germany','Bangladesh','USA','Australia'])
print(s1)
print(s2)

USA          1
UK           2
Germany      3
Australia    4
dtype: int64
Germany       1
Bangladesh    2
USA           3
Australia     4
dtype: int64


In [122]:
print(s1 + s2)      #operation is performed by grouping with same index name
print(s1 - s2)

Australia     8.0
Bangladesh    NaN
Germany       4.0
UK            NaN
USA           4.0
dtype: float64
Australia     0.0
Bangladesh    NaN
Germany       2.0
UK            NaN
USA          -2.0
dtype: float64


Dataframe Basics                    
1. Dataframes are the way to store data in rectangular grid.
2. Dataframe is defined as a 2d array
3. Three main components in dataframea: Data, Index, and Columns.

In [124]:
import pandas as pd
import numpy as np
l1 = [[1,2,3],[3,4,5],[5,6,7]]
arr1 = np.array(l1)
df1 = pd.DataFrame(l1)      #DF made from List
df2 = pd.DataFrame(arr1)    #DF made from Array


In [125]:
df1

0  1  2
0  1  2  3
1  3  4  5
2  5  6  7

In [126]:
df2

0  1  2
0  1  2  3
1  3  4  5
2  5  6  7

In [127]:
type(df1)

pandas.core.frame.DataFrame

In [132]:
print('shape',df1.shape)
print('index',df1.index)
print('values:',df1.values)
print('item:',df1.items)

shape (3, 3)
index RangeIndex(start=0, stop=3, step=1)
values: [[1 2 3]
 [3 4 5]
 [5 6 7]]
item: <bound method DataFrame.items of    0  1  2
0  1  2  3
1  3  4  5
2  5  6  7>


In [139]:
import pandas as pd
import numpy as np
l1 = [[1,2,3],[3,4,5],[5,6,7]]
df1 = pd.DataFrame(l1, index=['a','b','c'],columns=['c1','c2','c3'])    #custom index and column names
df1    

c1  c2  c3
a   1   2   3
b   3   4   5
c   5   6   7

Pandas project on Weather Report

In [144]:
import pandas as pd
d1 = pd.read_csv("G:/TUSHAR ANNAM/Python/datawithdarshil_python-for-data-engineering-main/python-for-data-engineering-main/4. Python Advance/data/weather_2012.csv")

In [145]:
d1

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0     2012-01-01 00:00:00      -1.8                -3.9           86   
1     2012-01-01 01:00:00      -1.8                -3.7           87   
2     2012-01-01 02:00:00      -1.8                -3.4           89   
3     2012-01-01 03:00:00      -1.5                -3.2           88   
4     2012-01-01 04:00:00      -1.5                -3.3           88   
...                   ...       ...                 ...          ...   
8779  2012-12-31 19:00:00       0.1                -2.7           81   
8780  2012-12-31 20:00:00       0.2                -2.4           83   
8781  2012-12-31 21:00:00      -0.5                -1.5           93   
8782  2012-12-31 22:00:00      -0.2                -1.8           89   
8783  2012-12-31 23:00:00       0.0                -2.1           86   

      Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)               Weather  
0                   4              8.0           101.24                   Fog  
1                   4              8.0           101.24                   Fog  
2                   7              4.0           101.26  Freezing Drizzle,Fog  
3                   6              4.0           101.27  Freezing Drizzle,Fog  
4                   7              4.8           101.23                   Fog  
...               ...              ...              ...                   ...  
8779               30              9.7           100.13                  Snow  
8780               24              9.7           100.03                  Snow  
8781               28              4.8            99.95                  Snow  
8782               28              9.7            99.91                  Snow  
8783               30             11.3            99.89                  Snow  

[8784 rows x 8 columns]

In [150]:
d1.head()

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0  2012-01-01 00:00:00      -1.8                -3.9           86   
1  2012-01-01 01:00:00      -1.8                -3.7           87   
2  2012-01-01 02:00:00      -1.8                -3.4           89   
3  2012-01-01 03:00:00      -1.5                -3.2           88   
4  2012-01-01 04:00:00      -1.5                -3.3           88   

   Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)               Weather  
0                4              8.0           101.24                   Fog  
1                4              8.0           101.24                   Fog  
2                7              4.0           101.26  Freezing Drizzle,Fog  
3                6              4.0           101.27  Freezing Drizzle,Fog  
4                7              4.8           101.23                   Fog

In [151]:
print(d1.shape)
print(d1.index)

(8784, 8)
RangeIndex(start=0, stop=8784, step=1)


In [154]:
d1['Date/Time'].head()      #dtype:object

0    2012-01-01 00:00:00
1    2012-01-01 01:00:00
2    2012-01-01 02:00:00
3    2012-01-01 03:00:00
4    2012-01-01 04:00:00
Name: Date/Time, dtype: object

In [156]:
type(d1['Date/Time'])       #since, single column is considered as series

pandas.core.series.Series

Converting series(single column) from object to datetime type to extract value from it.

In [159]:
d1['Date/Time'] = pd.to_datetime(d1['Date/Time'])

In [161]:
d1['Date/Time'].head()      #dtype:datetime

0   2012-01-01 00:00:00
1   2012-01-01 01:00:00
2   2012-01-01 02:00:00
3   2012-01-01 03:00:00
4   2012-01-01 04:00:00
Name: Date/Time, dtype: datetime64[ns]

Analysing the Dataframe

In [162]:
#info() function

d1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype         
---  ------              --------------  -----         
 0   Date/Time           8784 non-null   datetime64[ns]
 1   Temp (C)            8784 non-null   float64       
 2   Dew Point Temp (C)  8784 non-null   float64       
 3   Rel Hum (%)         8784 non-null   int64         
 4   Wind Spd (km/h)     8784 non-null   int64         
 5   Visibility (km)     8784 non-null   float64       
 6   Stn Press (kPa)     8784 non-null   float64       
 7   Weather             8784 non-null   object        
dtypes: datetime64[ns](1), float64(4), int64(2), object(1)
memory usage: 549.1+ KB


In [166]:
#head function

d1.head()   #bydefault gives first 5 rows

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0 2012-01-01 00:00:00      -1.8                -3.9           86   
1 2012-01-01 01:00:00      -1.8                -3.7           87   
2 2012-01-01 02:00:00      -1.8                -3.4           89   
3 2012-01-01 03:00:00      -1.5                -3.2           88   
4 2012-01-01 04:00:00      -1.5                -3.3           88   

   Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)               Weather  
0                4              8.0           101.24                   Fog  
1                4              8.0           101.24                   Fog  
2                7              4.0           101.26  Freezing Drizzle,Fog  
3                6              4.0           101.27  Freezing Drizzle,Fog  
4                7              4.8           101.23                   Fog

In [167]:
d1.head(10)     #first 10 rows

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0 2012-01-01 00:00:00      -1.8                -3.9           86   
1 2012-01-01 01:00:00      -1.8                -3.7           87   
2 2012-01-01 02:00:00      -1.8                -3.4           89   
3 2012-01-01 03:00:00      -1.5                -3.2           88   
4 2012-01-01 04:00:00      -1.5                -3.3           88   
5 2012-01-01 05:00:00      -1.4                -3.3           87   
6 2012-01-01 06:00:00      -1.5                -3.1           89   
7 2012-01-01 07:00:00      -1.4                -3.6           85   
8 2012-01-01 08:00:00      -1.4                -3.6           85   
9 2012-01-01 09:00:00      -1.3                -3.1           88   

   Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)               Weather  
0                4              8.0           101.24                   Fog  
1                4              8.0           101.24                   Fog  
2                7              4.0           101.26  Freezing Drizzle,Fog  
3                6              4.0           101.27  Freezing Drizzle,Fog  
4                7              4.8           101.23                   Fog  
5                9              6.4           101.27                   Fog  
6                7              6.4           101.29                   Fog  
7                7              8.0           101.26                   Fog  
8                9              8.0           101.23                   Fog  
9               15              4.0           101.20                   Fog

In [168]:
d1.tail()   #last 5 rows

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
8779 2012-12-31 19:00:00       0.1                -2.7           81   
8780 2012-12-31 20:00:00       0.2                -2.4           83   
8781 2012-12-31 21:00:00      -0.5                -1.5           93   
8782 2012-12-31 22:00:00      -0.2                -1.8           89   
8783 2012-12-31 23:00:00       0.0                -2.1           86   

      Wind Spd (km/h)  Visibility (km)  Stn Press (kPa) Weather  
8779               30              9.7           100.13    Snow  
8780               24              9.7           100.03    Snow  
8781               28              4.8            99.95    Snow  
8782               28              9.7            99.91    Snow  
8783               30             11.3            99.89    Snow

In [171]:
#index attribute

d1.index

RangeIndex(start=0, stop=8784, step=1)

In [174]:
d1['Weather']

0                        Fog
1                        Fog
2       Freezing Drizzle,Fog
3       Freezing Drizzle,Fog
4                        Fog
                ...         
8779                    Snow
8780                    Snow
8781                    Snow
8782                    Snow
8783                    Snow
Name: Weather, Length: 8784, dtype: object

In [175]:
#unique function

d1['Weather'].unique()  #arrays all the unique values.

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 

In [180]:
d1['Wind Spd (km/h)'].unique()

array([ 4,  7,  6,  9, 15, 13, 20, 22, 19, 24, 30, 35, 39, 32, 33, 26, 44,
       43, 48, 37, 28, 17, 11,  0, 83, 70, 57, 46, 41, 52, 50, 63, 54,  2],
      dtype=int64)

In [186]:
#nunique() function
#excludes NA values by default.
#gives the count of unique values.

d1['Wind Spd (km/h)'].nunique() 

34

In [187]:
len(d1['Wind Spd (km/h)'].unique())     #both are the same

34

In [188]:
#value_counts() function.
#it groups the same value rows and gives count of it.

d1['Weather'].value_counts()

Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                        

In [192]:
d1['Weather'].value_counts()[2]     #2nd index value

1728

In [194]:
#Q. find the number of times when the weather was clear

d1['Weather'].value_counts()['Clear']

1326

In [195]:
d1['Weather'].value_counts()[3]

1326

In [199]:
#Q. find the number of times when the wind speed was 4 km/h.

d1['Wind Spd (km/h)'].value_counts()[4]

474